= Creating a "DMG installer" for macOS

A DMG Installer is a convenient way to provide end-users a simple way to install
an application bundle. They are basically a folder with a shortcut to the Applications
directory, but they can be customized with icons, backgrounds, and layout properties.
A DMG file (.dmg) is a macOS Disk Image file, and it is used to package files or folders
providing compression, encryption, and read-only to the package.

== Creating The DMG File

=== Disk Utility

Type `Disk Utility` into Spotlite *CMD+SPACEBAR* from Finder
or from Terminal:
----
open /Applications/Utilities/Disk\ Utility.app/
----

*File* -&gt; *New Image* -&gt; *Image from Folder ... *
or *CMD+SHIFT+N*

Select the folder `MyApp.app/` when prompted then click `Image`.

In the `Save As` field enter a name for the file like `MyApp.dmg`.

From the `Image Format` drop-down select `read/write` then click `Save`.

== Command line:

----
hdiutil create -fs HFS+ -format UDRW -srcfolder dist/Polo.app -volname Polo Polo_UDRW.dmg
----

== Edit Folder Preferences

Mount the DMG and open it by double-clicking the file in Finder
or from Terminal:
----
open MyApp.dmg
open /Volumes/MyApp/
----

Create a link/shortcut to /Applications folder by right-clicking
on the `Applications` folder and selecting `Make Alias` then drag it into
the DMG folder or from Terminal:
----
cd /Volumes/MyApp/
ln -s /Applications Applications
----

In Finder press *CMD+1* to switch to icon view and arrange icons as needed.

Press *CMD+J* to show the View Options window and
adjust view settings as needed.

From `Background:` section choose `Picture` then
Drag and drop the image you want to use as the
background where it says `Drag image here`.

Unmount/Eject the DMG when finished with View Options
or from Terminal:
----
umount /Volumes/MyApp/
----

== Compress and convert to Read-only

From Disk Utility right-click on MyApp.dmg disk image and
select `Convert &quot;MyApp.dmg&quot;`.

In the `Save As` field enter a new name for the file like `MyAppfinal.dmg`.

From the `Image Format` drop-down select `read-only` then click `Save`
or from Terminal:
----
rm Polo.dmg
hdiutil convert -format UDZO -o Polo.dmg Polo_UDRW.dmg
----

Make writable:
----
rm Polo_UDRW.dmg
hdiutil convert -format UDRW -o Polo_UDRW.dmg Polo.dmg
hdiutil attach Polo_UDRW.dmg
rm -r /Volumes/Polo/Polo.app && cp -a dist/Polo.app /Volumes/Polo/
hdiutil detach /Volumes/Polo
----
Note: `cp -a dist/Polo.app`, no trailing "/" here.

== Application Grew Bigger And No Longer Fits

Resize the DMG:
----
hdiutil resize -size 1200m Polo_UDRW.dmg
hdiutil attach Polo_UDRW.dmg
rm -r /Volumes/Polo/Polo.app && cp -a dist/Polo.app /Volumes/Polo/
----

== FIN

Congratulations you are finished! Mount the new DMG to verify it is working properly.